name: balapil_family
description: Family Tree App for Ummar Khadeeja

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # State management & utils
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  uuid: ^4.5.1
  google_fonts: ^6.3.0
  url_launcher: ^6.1.10

  # Image & date
  image_picker: ^1.2.0
  intl: ^0.20.2

  # Cupertino icons (Web & iOS support)
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.14.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/ummar_khadeeja.jpg
    - assets/icons/

  fonts:
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo-Regular.ttf
